-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    CLIENTE_ID NUMBER(10) PRIMARY KEY,
    CLIENTE_NOME VARCHAR2(100) NOT NULL,
    CLIENTE_EMAIL VARCHAR2(100) NOT NULL,
    CLIENTE_TELEFONE VARCHAR2(15)
);

CREATE SEQUENCE CLIENTE_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela PRODUTO
CREATE TABLE PRODUTO (
    PRODUTO_ID NUMBER(10) PRIMARY KEY,
    PRODUTO_NOME VARCHAR2(100) NOT NULL,
    PRODUTO_DESCRICAO VARCHAR2(500),
    PRODUTO_PRECO NUMBER(10, 2) NOT NULL
);

CREATE SEQUENCE PRODUTO_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela PEDIDO
CREATE TABLE PEDIDO (
    PEDIDO_ID NUMBER(10) PRIMARY KEY,
    PEDIDO_STATUS VARCHAR2(50) NOT NULL,
    PEDIDO_DATA DATE NOT NULL,
    PEDIDO_CLIENTE_ID NUMBER(10) NOT NULL,
    PEDIDO_VLR_TOTAL NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (PEDIDO_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);

CREATE SEQUENCE PEDIDO_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela ITEM_PEDIDO
CREATE TABLE ITEM_PEDIDO (
    ITEM_PEDIDO_ID NUMBER(10) PRIMARY KEY,
    ITEM_PEDIDO_QTD NUMBER(10) NOT NULL,
    ITEM_PEDIDO_PRECO_UNITARIO NUMBER(10, 2) NOT NULL,
    ITEM_PEDIDO_PRODUTO_ID NUMBER(10) NOT NULL,
    ITEM_PEDIDO_PEDIDO_ID NUMBER(10) NOT NULL,
    FOREIGN KEY (ITEM_PEDIDO_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID),
    FOREIGN KEY (ITEM_PEDIDO_PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID)
);

CREATE SEQUENCE ITEM_PEDIDO_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela ENDERECO
CREATE TABLE ENDERECO (
    ENDERECO_ID NUMBER(10) PRIMARY KEY,
    ENDERECO_RUA VARCHAR2(200) NOT NULL,
    ENDERECO_CIDADE VARCHAR2(100) NOT NULL,
    ENDERECO_ESTADO VARCHAR2(50) NOT NULL,
    ENDERECO_CEP VARCHAR2(10) NOT NULL,
    ENDERECO_CLIENTE_ID NUMBER(10) NOT NULL,
    FOREIGN KEY (ENDERECO_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);

CREATE SEQUENCE ENDERECO_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela PAGAMENTO
CREATE TABLE PAGAMENTO (
    PAGAMENTO_ID NUMBER(10) PRIMARY KEY,
    PAGAMENTO_VALOR NUMBER(10, 2) NOT NULL,
    PAGAMENTO_DATA DATE NOT NULL,
    PAGAMENTO_PEDIDO_ID NUMBER(10) NOT NULL,
    PAGAMENTO_STATUS VARCHAR2(50) NOT NULL,
    FOREIGN KEY (PAGAMENTO_PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID)
);

CREATE SEQUENCE PAGAMENTO_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela CATEGORIA_PRODUTO
CREATE TABLE CATEGORIA_PRODUTO (
    CATEGORIA_ID NUMBER(10) PRIMARY KEY,
    CATEGORIA_NOME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE CATEGORIA_PRODUTO_SEQ START WITH 1 INCREMENT BY 1;

-- Tabela de Relacionamento PRODUTO_CATEGORIA
CREATE TABLE PRODUTO_CATEGORIA (
    PRODUTO_ID NUMBER(10) NOT NULL,
    CATEGORIA_ID NUMBER(10) NOT NULL,
    PRIMARY KEY (PRODUTO_ID, CATEGORIA_ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA_PRODUTO(CATEGORIA_ID)
);